# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(340, 400)
        MainScreen.setMinimumSize(QtCore.QSize(340, 400))
        MainScreen.setMaximumSize(QtCore.QSize(340, 400))
        font = QtGui.QFont()
        font.setFamily("LMSansQuot8")
        font.setItalic(True)
        MainScreen.setFont(font)
        MainScreen.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(239, 239, 239, 255), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_saveword = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_saveword.sizePolicy().hasHeightForWidth())
        self.btn_saveword.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setItalic(False)
        self.btn_saveword.setFont(font)
        self.btn_saveword.setStyleSheet("background-color: rgb(236, 236, 236)")
        self.btn_saveword.setObjectName("btn_saveword")
        self.verticalLayout.addWidget(self.btn_saveword)
        self.btn_dictionary = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dictionary.sizePolicy().hasHeightForWidth())
        self.btn_dictionary.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setItalic(False)
        self.btn_dictionary.setFont(font)
        self.btn_dictionary.setStyleSheet("background-color: rgb(236, 236, 236)")
        self.btn_dictionary.setObjectName("btn_dictionary")
        self.verticalLayout.addWidget(self.btn_dictionary)
        self.btn_settings = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setItalic(False)
        self.btn_settings.setFont(font)
        self.btn_settings.setStyleSheet("background-color: rgb(236, 236, 236)")
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout.addWidget(self.btn_settings)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.lbl_version = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setItalic(False)
        self.lbl_version.setFont(font)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout.addWidget(self.lbl_version)
        MainScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainScreen)
        self.btn_settings.clicked.connect(MainScreen.btn_settings_clicked)
        self.btn_saveword.clicked.connect(MainScreen.btn_saveword_clicked)
        self.btn_dictionary.clicked.connect(MainScreen.btn_dictionary_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "Laside"))
        self.btn_saveword.setText(_translate("MainScreen", "Save Word"))
        self.btn_dictionary.setText(_translate("MainScreen", "Dictionary"))
        self.btn_settings.setText(_translate("MainScreen", "Settings"))
        self.lbl_version.setText(_translate("MainScreen", "Version 1.0"))

